export const home = (req,res) => res.send('Users')
export const editProfile = (req,res) => res.send('Edit profile')
export const changePassword = (req,res) => res.send('Change Password')
export const userDetail = (req,res) => res.send('Users Detail')
export const join = (req,res) => res.send('Join')
export const login = (req,res) => res.send('Login')
export const logout = (req,res) => res.send('Logout')